Repository AY2021S1-CS2103T-W12-3/tp, pull requests merged in 2020-10, with the labels that each got.

#153 Add table of contents to DG and minor fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/LogicClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Chore

#156 Add About section to UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Chore

#172 Add MarkAppointmentAsDone functionalities
  docs/UserGuide.md
  docs/UserGuide.pdf
  src/main/java/team/baymax/commons/core/time/DateTime.java
  src/main/java/team/baymax/logic/commands/appointment/MarkAppointmentDoneCommand.java
  src/main/java/team/baymax/logic/parser/AppointmentBookParser.java
  src/main/java/team/baymax/logic/parser/appointment/MarkAppointmentDoneCommandParser.java
  src/main/java/team/baymax/model/appointment/Appointment.java
  src/main/java/team/baymax/model/listmanagers/AppointmentManager.java
  src/test/java/team/baymax/model/appointment/AppointmentTest.java
Labels: priority.High

#183 Add Schedule View
  src/main/java/team/baymax/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/team/baymax/model/calendar/AppointmentCalendar.java
  src/main/java/team/baymax/model/util/datetime/Time.java
  src/main/java/team/baymax/ui/CalendarPage.java
  src/main/java/team/baymax/ui/ScheduleCard.java
  src/main/java/team/baymax/ui/ScheduleListPanel.java
  src/main/java/team/baymax/ui/SchedulePage.java
  src/main/java/team/baymax/ui/SchedulePanel.java
  src/main/java/team/baymax/ui/SideTabPane.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ScheduleListPanel.fxml
  src/main/resources/view/SchedulePage.css
  src/main/resources/view/SchedulePage.fxml
  src/main/resources/view/SchedulePanel.css
  src/main/resources/view/SchedulePanel.fxml
Labels: type.Enhancement

#184 Add appointment by patient NRIC
  src/main/java/team/baymax/MainApp.java
  src/main/java/team/baymax/commons/util/StringUtil.java
  src/main/java/team/baymax/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/team/baymax/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/team/baymax/logic/commands/appointment/FindAppointmentByKeywordCommand.java
  src/main/java/team/baymax/logic/commands/appointment/MarkAppointmentDoneCommand.java
  src/main/java/team/baymax/logic/commands/patient/FindPatientCommand.java
  src/main/java/team/baymax/logic/parser/CliSyntax.java
  src/main/java/team/baymax/logic/parser/ParserUtil.java
  src/main/java/team/baymax/logic/parser/appointment/AddAppointmentCommandParser.java
  src/main/java/team/baymax/model/appointment/AppointmentContainsKeywordPredicate.java
  src/main/java/team/baymax/model/appointment/SameDatetimeAndPatientPredicate.java
  src/main/java/team/baymax/model/modelmanagers/PatientManager.java
  src/main/java/team/baymax/model/util/TabId.java
  src/test/java/team/baymax/logic/commands/appointment/AddAppointmentCommandTest.java
Labels: type.Bug, type.Enhancement

#191 Package UI classes
  src/main/java/team/baymax/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/team/baymax/logic/parser/appointment/AddAppointmentCommandParser.java
  src/main/java/team/baymax/ui/SideTabPane.java
  src/main/java/team/baymax/ui/appointment/AppointmentCard.java
  src/main/java/team/baymax/ui/appointment/AppointmentInfoPage.java
  src/main/java/team/baymax/ui/appointment/AppointmentListPanel.java
  src/main/java/team/baymax/ui/calendar/CalendarPage.java
  src/main/java/team/baymax/ui/calendar/SchedulePage.java
  src/main/java/team/baymax/ui/calendar/SchedulePanel.java
  src/main/java/team/baymax/ui/dashboard/Dashboard.java
  src/main/java/team/baymax/ui/dashboard/DigitalClock.java
  src/main/java/team/baymax/ui/patient/PatientCard.java
  src/main/java/team/baymax/ui/patient/PatientInfoPage.java
  src/main/java/team/baymax/ui/patient/PatientListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/appointment/AppointmentInfoPage.fxml
  src/main/resources/view/appointment/AppointmentListCard.fxml
  src/main/resources/view/appointment/AppointmentListPanel.fxml
  src/main/resources/view/calendar/CalendarPage.css
  src/main/resources/view/calendar/CalendarPage.fxml
  src/main/resources/view/calendar/ScheduleListCard.fxml
  src/main/resources/view/calendar/SchedulePage.css
  src/main/resources/view/calendar/SchedulePage.fxml
  src/main/resources/view/calendar/SchedulePanel.css
  src/main/resources/view/calendar/SchedulePanel.fxml
  src/main/resources/view/dashboard/Dashboard.css
  src/main/resources/view/dashboard/Dashboard.fxml
  src/main/resources/view/patient/PatientInfoPage.fxml
  src/main/resources/view/patient/PatientListCard.fxml
  src/main/resources/view/patient/PatientListPanel.fxml
Labels: type.Bug, type.Chore
